### ISSUE TITLE
-outfile 参数报错

### ISSUE THREAD

**Issue by timwhitez** [YagamiiLight/Cerberus#4]
Traceback (most recent call last):
  File "C:\Python37\Python37-32\lib\logging\config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "C:\Python37\Python37-32\lib\logging\config.py", line 735, in configure_handler
    result = factory(**kwargs)
  File "C:\Python37\Python37-32\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python37\Python37-32\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\timwhite\\Desktop\\Cerberus-master\\Cerberus-master\\2020-01-29 23:17:32_http:\\www.airbnb.com_.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\cerberus.py", line 91, in <module>
    sub = subdomain(target, file = "DNSPod.txt", logger_type = logger_type)
  File "C:\Users\timwhite\Desktop\Cerberus-master\Cerberus-master\core\subdomain.py", line 20, in __init__
    self.logger = factory_logger(logger_type, target, 'subdomain')
  File "C:\Users\timwhite\Desktop\Cerberus-master\Cerberus-master\core\log.py", line 201, in factory_logger
    logging.config.dictConfig(config_file)
  File "C:\Python37\Python37-32\lib\logging\config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python37\Python37-32\lib\logging\config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'file'

**Comment by timwhitez** [comment]
<img width="712" alt="error" src="https://user-images.githubusercontent.com/36320909/73371698-0401cd80-42f1-11ea-881d-0b517db2e62e.png">

**Comment by zhou0718** [comment]
xd,我也遇到这个问题了，能分享下你怎么解决的🐎？

**Comment by zhou0718** [comment]
xd,我也遇到这个问题了，能分享下你怎么解决的🐎？ @timwhitez
