### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by niuqun2003** [YagamiiLight/Cerberus#8]
Traceback (most recent call last):
  File "cerberus.py", line 48, in <module>
    from core.proxies import Proxy
  File "C:\Program Files\python\Cerberus\core\proxies.py", line 2, in <module>
    from core import regex
  File "C:\Program Files\python\Cerberus\core\regex.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by ityangbaojin** [comment]
没有requests模块, pip3 install requests
